from distutils.core import setup

setup(
    name='flask-restplus-relative-swagger',
    version='2.0',
    description='Flask-RESTplus (Flask-RESTX) manual path assignment for Swagger assets, '
                'it changes the relative path for Swagger assets generated by Flask-RESTplus framework',
    license='BSD',
    author='Aaron Estrada Poggio',
    author_email='aaron.estrada.poggio@gmail.com',
    url='https://github.com/aaronestrada/flask-restplus-swagger-relative',
    packages=['flask_restplus_relative_swagger'],
    python_requires='>=3.6',
    install_requires=[
        'Flask>=2.0.3',
        'flask-restx>=0.5.1'
    ]
)
